CREATE TABLE eps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE eps_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eps_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    eps_name VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_eps_plan_code UNIQUE (eps_id, code),
    CONSTRAINT fk_eps_plan_eps FOREIGN KEY (eps_id) REFERENCES eps(id)
);

CREATE TABLE user_insurance_affiliations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_insurance_plan UNIQUE (user_id, plan_id),
    CONSTRAINT fk_affiliation_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_affiliation_plan FOREIGN KEY (plan_id) REFERENCES eps_plans(id)
);

INSERT INTO eps (code, name, active) VALUES
    ('EPS_DEMO_A', 'EPS Demo A', TRUE),
    ('EPS_DEMO_B', 'EPS Demo B', TRUE);

INSERT INTO eps_plans (eps_id, code, eps_name, name, active)
SELECT id, 'PLAN_DEMO_1', name, 'Plan Demo 1', TRUE FROM eps WHERE code = 'EPS_DEMO_A';
INSERT INTO eps_plans (eps_id, code, eps_name, name, active)
SELECT id, 'PLAN_DEMO_2', name, 'Plan Demo 2', TRUE FROM eps WHERE code = 'EPS_DEMO_A';
INSERT INTO eps_plans (eps_id, code, eps_name, name, active)
SELECT id, 'PLAN_INTEGRAL', name, 'Plan Integral Demo', TRUE FROM eps WHERE code = 'EPS_DEMO_B';
INSERT INTO eps_plans (eps_id, code, eps_name, name, active)
SELECT id, 'PLAN_RETIRED', name, 'Plan Retirado', FALSE FROM eps WHERE code = 'EPS_DEMO_B';
