CREATE TABLE appointment_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL
);

CREATE TABLE specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    is_general BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    reason VARCHAR(500),
    scheduled_start_at TIMESTAMP NOT NULL,
    scheduled_end_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_user_id) REFERENCES users(id),
    CONSTRAINT fk_appointment_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id),
    CONSTRAINT fk_appointment_status FOREIGN KEY (status_id) REFERENCES appointment_statuses(id)
);

CREATE TABLE professional_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    appointment_id BIGINT,
    CONSTRAINT uq_professional_slot UNIQUE (professional_id, start_at),
    CONSTRAINT fk_slot_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);

INSERT INTO appointment_statuses (code, name) VALUES ('REQUESTED', 'Solicitada'), ('APPROVED', 'Aprobada');
INSERT INTO specialties (code, name, is_general, active) VALUES
    ('GENERAL', 'Medicina General', TRUE, TRUE),
    ('CARDIOLOGY', 'Cardiología', FALSE, TRUE);

INSERT INTO professional_slots (professional_id, location_id, start_at, end_at) VALUES
    (1, 1, TIMESTAMP '2030-01-15 08:00:00', TIMESTAMP '2030-01-15 08:30:00'),
    (1, 1, TIMESTAMP '2030-01-15 08:30:00', TIMESTAMP '2030-01-15 09:00:00'),
    (1, 1, TIMESTAMP '2030-01-15 09:00:00', TIMESTAMP '2030-01-15 09:30:00'),
    (1, 1, TIMESTAMP '2030-01-15 09:30:00', TIMESTAMP '2030-01-15 10:00:00');
